// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGDeYJR0aA7BmAfC-gsFsUrH1xpwBUi7c',
    appId: '1:84274712485:web:1432bb2c3c3bd36193a24c',
    messagingSenderId: '84274712485',
    projectId: 'furniture-app-96620',
    authDomain: 'furniture-app-96620.firebaseapp.com',
    storageBucket: 'furniture-app-96620.appspot.com',
    measurementId: 'G-BH4HP6EQXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGeXQYHugwKkOIbaMTDNXnIFYwQuqO6ZY',
    appId: '1:84274712485:android:9592913be48056a293a24c',
    messagingSenderId: '84274712485',
    projectId: 'furniture-app-96620',
    storageBucket: 'furniture-app-96620.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXIc1lGQbPT4yzgG0XLmsq8SHzuSWWpSk',
    appId: '1:84274712485:ios:b9dc1d963900c19a93a24c',
    messagingSenderId: '84274712485',
    projectId: 'furniture-app-96620',
    storageBucket: 'furniture-app-96620.appspot.com',
    iosClientId: '84274712485-05nk10ljda1dhofvga4bd997u0r8o0kg.apps.googleusercontent.com',
    iosBundleId: 'com.example.practice1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXIc1lGQbPT4yzgG0XLmsq8SHzuSWWpSk',
    appId: '1:84274712485:ios:9943d80e2c37c8a793a24c',
    messagingSenderId: '84274712485',
    projectId: 'furniture-app-96620',
    storageBucket: 'furniture-app-96620.appspot.com',
    iosClientId: '84274712485-agsn791aj9n6jr8abl81pbqdks0l0nj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.practice1.RunnerTests',
  );
}
